name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'deps'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'github-actions'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Container Images

  - `ghcr.io/$OWNER/$REPOSITORY:v$RESOLVED_VERSION`
  - `ghcr.io/$OWNER/$REPOSITORY:latest`

  ## Installation

  ```bash
  pip install machine-learning-model==$RESOLVED_VERSION
  ```

  Or use Docker:

  ```bash
  docker run ghcr.io/$OWNER/$REPOSITORY:v$RESOLVED_VERSION
  ```
