version: '3.8'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
      - /app/venv  # Exclude venv from mount
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    depends_on:
      - redis
      - postgres

  ml-gui:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.gui
    image: ml-model-gui:latest
    container_name: ml-model-gui
    environment:
      - DISPLAY=${DISPLAY}
      - QT_SCALE_FACTOR=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./:/app:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    stdin_open: true
    tty: true

  ml-agent:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.gui
    image: ml-model-agent:latest
    container_name: ml-model-agent
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      - ./:/app:rw
    command: ["bash","-lc","./run_agent.sh"]
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
