version: '3.8'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
      - /app/venv  # Exclude venv from mount
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    # ports:
    #   - "8000:8000"
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
